# nginx/nginx.conf
server {
    listen 80;

    server_name comrade.name.ng www.comrade.name.ng;


    # 1. Route all standard traffic to the frontend container
    location / {
        # 'frontend' is the name of the service in docker-compose
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 2. Route any traffic starting with /api to the backend container
    location /api/ {
        # 'backend' is the name of the service in docker-compose
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}